apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: headless
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  clusterIP: None
  ports:
    - name: "9095"
      port: 9095
      targetPort: 3306
  selector:
    io.kompose.service: db
  type: ClusterIP
status:
  loadBalancer: {}
